# Generated by Django 3.2.6 on 2021-08-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
