# Generated by Django 3.2.6 on 2021-08-05 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_blog_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='votes',
        ),
        migrations.AddField(
            model_name='blog',
            name='authors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='blog_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='blog_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
